import { useState, useEffect, useRef } from "react";

const QUESTIONS = [
  {id:1,section:"A",level:"N5",question:"あした、ともだち（ ）えいがを 見ます。",options:["に","と","を","へ"],correctIndex:1,explanations:{correct:"We use 'と' here because 'と' means 'with' when you are doing an action together with another person!",wrongOptions:["に is completely wrong here because 'に' shows a destination or a specific time, not a person you do things with.","を is incorrect because 'を' marks the object you are watching (which is already 'えいが'), so we cannot use it twice like this.","へ is wrong because 'へ' shows direction towards a physical location, and a friend is not a place you can travel towards."]}},
  {id:2,section:"A",level:"N5",question:"つくえの うえ（ ）ほんが あります。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because 'に' points to the exact location where something exists when using existence verbs like 'あります'!",wrongOptions:["で is completely wrong because 'で' is used for actions taking place at a location, but 'exist' is a state, not an active action.","を is incorrect because 'を' marks a direct object receiving an action, but 'あります' does not take a direct object.","が is wrong because 'が' marks the subject that exists (which is already 'ほん'), not the place where it sits."]}},
  {id:3,section:"A",level:"N5",question:"きのう、デパート（ ）くつを かいました。",options:["に","へ","で","を"],correctIndex:2,explanations:{correct:"We use 'で' here because 'で' marks the physical location where an active event or action like buying takes place!",wrongOptions:["に is completely wrong because 'に' shows where something stays or sits, not where an active shopping action happens.","へ is incorrect because 'へ' indicates direction towards a place, but we are not traveling towards the department store in this action.","を is wrong because 'を' marks the direct object being bought (which is already 'くつ'), so we can't use it for the location."]}},
  {id:4,section:"A",level:"N5",question:"わたしは 毎日 日本語（ ）べんきょうします。",options:["が","を","に","と"],correctIndex:1,explanations:{correct:"We use 'を' here because '日本語' (Japanese language) is the direct object that is being actively studied!",wrongOptions:["が is completely wrong because 'が' marks the subject performing the action, but Japanese is the topic being studied, not the person studying.","に is incorrect because 'に' is for times, destinations, or targets, but studying does not treat a language as a movement destination.","と is wrong because 'と' means 'with', which would hilariously mean you are studying side-by-side with a physical person named Japanese."]}},
  {id:5,section:"A",level:"N5",question:"こうえん（ ）さんぽします。",options:["を","に","で","へ"],correctIndex:0,explanations:{correct:"We use 'を' here because verbs of motion through space like 'さんぽします' (to stroll) use 'を' to mark the area you move through!",wrongOptions:["に is completely wrong because 'に' implies arriving at a final point, rather than moving along paths inside a park.","で is incorrect because while 'で' means action location, standard Japanese grammar prioritizes 'を' for spaces you walk through or pass along.","へ is wrong because 'へ' marks the direction toward a destination, but walking within a park means you are already inside it."]}},
  {id:6,section:"A",level:"N5",question:"教室（きょうしつ）に 先生（ ）います。",options:["は","が","を","に"],correctIndex:1,explanations:{correct:"We use 'が' here because 'が' marks the subject that exists when using the existence verb 'います' for living things!",wrongOptions:["は is incorrect here because '教室に' already establishes our location, and 'が' introducing new information or presence fits perfectly.","を is completely wrong because 'います' is an intransitive verb meaning 'to exist', so it can never take a direct object with 'を'.","に is wrong because 'に' marks the location (which is already marked by '教室に'), so we can't label the teacher as a location."]}},
  {id:7,section:"A",level:"N5",question:"鈴木さんは 毎朝 7時（ ）家を出ます。",options:["に","で","を","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because 'に' is the specific target particle used to point to an exact, numerical clock time like 7:00!",wrongOptions:["で is completely wrong because 'で' is used for a location where an action happens, not for clock times.","を is incorrect because 'を' marks the direct object receiving an action, it cannot pin down a time slot.","へ is wrong because 'へ' shows direction towards a place (like 'heading towards school'), not a point in time."]}},
  {id:8,section:"A",level:"N5",question:"この りんごは 一つ 100円（ ）です。",options:["に","で","が","を"],correctIndex:1,explanations:{correct:"We use 'で' here because 'で' acts as a particle indicating a limit, cost, or unit basis for quantities and prices!",wrongOptions:["に is completely wrong because 'に' shows time points or specific targets, not the financial unit rate of items.","が is incorrect because 'が' marks the primary subject of a sentence, but 100 yen is the cost description, not the item itself.","を is wrong because 'を' marks objects receiving physical actions, but simply being a specific price requires no action particle."]}},
  {id:9,section:"A",level:"N5",question:"バス（ ）会社へ 行きます。",options:["に","で","を","へ"],correctIndex:1,explanations:{correct:"We use 'で' here because 'で' is the particle used to point out the tool, means, or vehicle used to do an action!",wrongOptions:["に is completely wrong because 'に' marks the destination or time, but you are riding the bus, not traveling inside time or to a bus city.","を is incorrect because 'を' would mean you are physically grabbing the entire bus and doing an action to it like a toy.","へ is wrong because 'へ' indicates direction towards a destination, but the bus is your ride, not your travel destination."]}},
  {id:10,section:"A",level:"N5",question:"日曜日（ ）ともだちの 家に行きました。",options:["に","で","を","は"],correctIndex:0,explanations:{correct:"We use 'に' here because specific days of the week like Sunday (日曜日) take 'に' to show exactly when an action happened!",wrongOptions:["で is completely wrong because 'で' marks where an action happens or what tool you used, not specific calendar days.","を is incorrect because days of the week cannot be the direct object of a movement verb like going.","は is less accurate here because we are stating the specific time coordinate rather than creating a broad contrastive topic about Sundays."]}},
  {id:11,section:"A",level:"N5",question:"おとうとは 部屋（へや）（ ）すわっています。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because the verb 'すわります' (to sit) takes 'に' to show the final location where the body settles down!",wrongOptions:["で is incorrect because 'で' is for active, moving actions, but sitting down is a state of settling onto a specific spot.","を is completely wrong because a room cannot be the direct physical object of a sitting action.","が is wrong because the younger brother is the subject sitting down, not the physical room itself."]}},
  {id:12,section:"A",level:"N5",question:"お母さんは 台所（だいどころ）（ ）料理を作っています。",options:["に","で","を","へ"],correctIndex:1,explanations:{correct:"We use 'で' here because cooking (料理を作っています) is a highly active process occurring inside a designated workspace!",wrongOptions:["に is completely wrong because 'に' is for simple presence or destination, but here an active meal preparation is happening.","を is incorrect because the kitchen is the room where things happen, not the literal food ingredient being chopped up.","へ is wrong because 'へ' means traveling towards a location, but mom is already there actively making food."]}},
  {id:13,section:"A",level:"N5",question:"かれは 英語（ ）上手の（じょうず）です。",options:["を","が","に","で"],correctIndex:1,explanations:{correct:"We use 'が' here because skill adjectives like '上手' (skillful/good at) always use 'が' to mark the specific field of expertise!",wrongOptions:["を is completely wrong because '上手' is a descriptive adjective, not an action verb, so it can never take 'を'.","に is incorrect because 'に' doesn't mark the subject area of skill or talent sentences in standard basic grammar.","で is wrong because 'で' would mean 'by means of English', which does not fit the structure of stating what someone is good at."]}},
  {id:14,section:"A",level:"N5",question:"私は 海（うみ）（ ）行きたいです。",options:["を","が","へ","で"],correctIndex:2,explanations:{correct:"We use 'へ' here because it directly indicates the spatial direction and destination toward which you want to travel!",wrongOptions:["を is completely wrong because '行きたい' (want to go) is a motion verb and doesn't take a direct object here.","が is incorrect because the ocean is not the subject performing an action; it's the target destination.","で is wrong because 'で' marks where an action happens, but you haven't arrived at the ocean yet to do anything there."]}},
  {id:15,section:"A",level:"N5",question:"ペン（ ）手紙（てがみ）を書きます。",options:["で","に","を","が"],correctIndex:0,explanations:{correct:"We use 'で' here because the pen is the physical tool or instrument used to execute the action of writing!",wrongOptions:["に is completely wrong because 'に' would imply writing directly onto the surface of the pen itself, which is not what's happening.","を is incorrect because '手紙' (letter) is already the object being written, so the pen cannot be the object.","が is wrong because the pen isn't the alive subject doing the actual writing; a person is."]}},
  {id:16,section:"A",level:"N5",question:"あのビルは 木（ ）作られました。",options:["を","に","で","が"],correctIndex:2,explanations:{correct:"We use 'で' here because 'で' is used to identify the physical material (wood) out of which an object is constructed!",wrongOptions:["を is completely wrong because the building is already the subject, and wood is the material, not the active receiver of an action here.","に is incorrect because material components are not point locations or time deadlines.","が is wrong because wood isn't the active agent or independent subject constructing the building by itself."]}},
  {id:17,section:"A",level:"N5",question:"飛行機（ひこうき）（ ）日本へ 来ました。",options:["に","で","を","へ"],correctIndex:1,explanations:{correct:"We use 'で' here because the airplane is the mode of transportation and vehicle method used to move across locations!",wrongOptions:["に is completely wrong because 'に' would imply you are arriving inside the airplane as a destination, rather than using it to reach Japan.","を is incorrect because you are not manipulating or acting upon the airplane as a direct object.","へ is wrong because 'へ' marks the direction, which is already correctly taken by '日本へ'."]}},
  {id:18,section:"A",level:"N5",question:"こうえん（ ）犬が 走っています。",options:["に","で","を","へ"],correctIndex:1,explanations:{correct:"We use 'で' here because running around (走っています) is an active physical exercise happening within the borders of the park!",wrongOptions:["に is incorrect because 'に' implies simple static existence, but running is a continuous dynamic action happening in a location.","を is incorrect here because the dog is running *inside* the park bounds as its location of action, not crossing across it to leave.","へ is wrong because the dog is already inside the park running around, not running towards the park from somewhere else."]}},
  {id:19,section:"A",level:"N5",question:"私は まだ 漢字（ ）わかりません。",options:["を","が","に","で"],correctIndex:1,explanations:{correct:"We use 'が' here because the verb 'わかります' (to understand) is a potential-state verb that natively requires 'が' to mark its object!",wrongOptions:["を is completely wrong because 'わかります' represents a state of understanding, and state verbs in basic Japanese cannot take 'を'.","に is incorrect because 'に' marks a location or time, not the topic matter that you understand or don't understand.","で is wrong because kanji is not the physical tool or place used to perform an understanding action."]}},
  {id:20,section:"A",level:"N5",question:"田中さんは 図書館（としょかん）（ ）本を かしました。",options:["に","で","へ","を"],correctIndex:1,explanations:{correct:"We use 'で' here because lending books out is an active transactional event that happens inside the physical building of the library!",wrongOptions:["に is incorrect because 'に' would imply lending books *to* the library as an entity, but here it's the venue where the lending event occurs.","へ is wrong because 'へ' shows motion toward a place, but lending is a stationary transaction happening inside.","を is completely wrong because '本' (book) is already the object being lent out, so we can't label the library with 'を'."]}},
  {id:21,section:"A",level:"N5",question:"来週（らいしゅう）の 水曜日（ ）テストがあります。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because specific, named calendar days like Wednesday (水曜日) require 'に' to point to the scheduled time!",wrongOptions:["で is completely wrong because 'で' marks action locations or methods, not specific times on a calendar.","を is incorrect because a test date is not a physical direct object that you can grab or manipulate.","が is wrong because 'テスト' is already the subject marked by 'が' that exists, so we cannot mark the day with it."]}},
  {id:22,section:"A",level:"N5",question:"駅（えき）（ ）ともだちを 待ちます。",options:["に","で","を","へ"],correctIndex:1,explanations:{correct:"We use 'で' here because waiting for someone (待ちます) is an active mental/physical effort happening at a specific venue!",wrongOptions:["に is incorrect because '待ちます' is treated as an active event taking place at a location, requiring 'で' instead of static 'に'.","を is completely wrong because 'ともだち' (friend) is already the object being waited for, so the station cannot take 'を'.","へ is wrong because 'へ' implies you are currently traveling toward the station, but you are already there waiting."]}},
  {id:23,section:"A",level:"N5",question:"お父さんは 毎晩 おさけ（ ）飲みます。",options:["が","に","を","で"],correctIndex:2,explanations:{correct:"We use 'を' here because 'おさけ' (alcohol) is the direct physical substance being consumed by the action verb '飲みます'!",wrongOptions:["が is incorrect here because the father is the main subject drinking, not the sake itself doing any drinking.","に is completely wrong because sake is not a destination or a specific numerical clock time point.","で is wrong because 'で' would mean you are using alcohol as a physical tool or room to perform another action."]}},
  {id:24,section:"A",level:"N5",question:"この道を まっすぐ（ ）行ってください。",options:["に","を","で","へ"],correctIndex:1,explanations:{correct:"We use 'を' here because space-motion verbs like '行ってください' (please go) use 'を' to mark the path or route being traversed!",wrongOptions:["に is incorrect because 'に' would mark a final arrival stop, but the road is the continuous path you are walking along.","で is completely wrong because you are moving along the path, and standard motion rules for routes require 'を'.","へ is wrong because you are navigating down the route itself, not traveling toward a city named 'This Road'."]}},
  {id:25,section:"A",level:"N5",question:"木村さんは テニス（ ）することが 好きです。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because 'テニスをする' means 'to do tennis', where tennis is the direct object of the active verb 'する'!",wrongOptions:["が is incorrect here because 'が' already appears later in 'することが好き' to mark the preference; we need 'を' to tie tennis to its action verb.","に is completely wrong because sports aren't time stamps or geographic travel locations.","で is wrong because 'で' would mean doing an action by means of a tennis ball, but here 'tennis' is the sport activity itself."]}},
  {id:26,section:"A",level:"N5",question:"私の部屋は あまり 広（ ）ないです。",options:["く","で","に","だ"],correctIndex:0,explanations:{correct:"We use 'く' here because to make an い-adjective like '広い' negative, we must drop the final 'い' and add 'くない'!",wrongOptions:["で is completely wrong because 'で' is used for combining な-adjectives or nouns, never for い-adjectives.","に is incorrect because 'に' changes い-adjectives into adverbs, but we are trying to create a flat negative description here.","だ is wrong because 'だ' is the plain form of 'です' and cannot be stuffed in the middle of a negative い-adjective."]}},
  {id:27,section:"A",level:"N5",question:"あのカメラは とても （ ）です。",options:["高い","高いく","高に","高だ"],correctIndex:0,explanations:{correct:"We use '高い' (expensive) in its base dictionary form because it directly precedes 'です' to cleanly describe a noun!",wrongOptions:["高いく is a completely made-up non-existent word form that violates basic Japanese grammar rules.","高に is incorrect because adjectives do not take 'に' when they are simply ending a sentence with 'です'.","高だ is wrong because combining an い-adjective directly with 'だ' or changing its root like this is grammatically impossible."]}},
  {id:28,section:"A",level:"N5",question:"昨日（きのう）は 天気（てんき）が （ ）です。",options:["いい","よかったです","よかった","よく"],correctIndex:2,explanations:{correct:"We use 'よかった' here because 'yesterday' (昨日) requires the past tense of 'いい' (good), which is irregular and becomes 'よかった'!",wrongOptions:["いい is incorrect because 'いい' is strictly present tense, but the sentence clearly starts with 'yesterday'.","よかったです is grammatically redundant because 'です' is already printed right after the blank in the sentence prompt.","よく is wrong because 'よく' is the adverbial or connective form, not the completed past-tense modifier."]}},
  {id:29,section:"A",level:"N5",question:"この おかしは （ ）おいしいです。",options:["甘くて","甘いで","甘に","甘くで"],correctIndex:0,explanations:{correct:"We use '甘くて' because to link multiple い-adjectives together ('sweet and delicious'), we change the first one's ending to 'くて'!",wrongOptions:["甘いで is completely wrong because 'で' is strictly reserved for linking な-adjectives and nouns, never い-adjectives.","甘に is incorrect because 'に' creates an adverb, which cannot naturally string two descriptive adjectives together this way.","甘くで is a totally incorrect blended form that doesn't exist in standard Japanese conjugation."]}},
  {id:30,section:"A",level:"N5",question:"図書館（としょかん）では しずか（ ）してください。",options:["に","で","な","を"],correctIndex:0,explanations:{correct:"We use 'に' here because to turn a な-adjective like 'しずか' (quiet) into an adverb ('quietly') before the verb 'する', we add 'に'!",wrongOptions:["で is incorrect because 'で' indicates a location of action, but here we are modifying the target state of the verb 'してください'.","な is wrong because 'な' is only used when a noun directly follows immediately after it, but here a verb follows.","を is completely wrong because 'しずか' is a descriptive adjective state, not a noun object that you can physically grab."]}},
  {id:31,section:"A",level:"N5",question:"ゆうべ、テレビを 2時間（ ）見ました。",options:["ごろ","ぐらい","しか","まで"],correctIndex:1,explanations:{correct:"We use 'ぐらい' here because 'ぐらい' represents an approximate duration or length of time ('about 2 hours')!",wrongOptions:["ごろ is completely wrong because 'ごろ' is only used for specific single points on a clock (like 'around 2 o'clock'), never for total duration.","しか is incorrect because 'しか' means 'only' and requires a negative verb form at the end, but '見ました' is positive.","まで is wrong because 'まで' means 'until', which does not make sense right after a specific quantity of elapsed hours."]}},
  {id:32,section:"A",level:"N5",question:"私の 国から 日本まで 飛行機で 5時間（ ）かかります。",options:["ぐらい","から","まで","に"],correctIndex:0,explanations:{correct:"We use 'ぐらい' here because estimating travel time intervals ('takes about 5 hours') perfectly calls for an approximate quantity marker!",wrongOptions:["から is incorrect because 'から' means 'from', and the sentence already has '国から' earlier, making another one here nonsense.","まで is wrong because 'まで' means 'until', but we are measuring the grand total duration of hours, not a endpoint.","に is completely wrong because duration time spans do not take the specific point-time particle 'に'."]}},
  {id:33,section:"A",level:"N5",question:"木村さんは 今日（ ）来ませんでした。",options:["は","が","を","に"],correctIndex:0,explanations:{correct:"We use 'は' here because it highlights '今日' (today) as our main topic of contrast, emphasizing that today specifically he didn't show up!",wrongOptions:["が is incorrect here because '今日' is a time word and cannot function as the active subject that performs the action of coming.","を is completely wrong because time cannot be a direct object that is physically acted upon by the verb '来ませんでした'.","に is wrong because relative time words like '今日', '明日', or '昨日' never take the point-particle 'に'."]}},
  {id:34,section:"A",level:"N5",question:"こうえんに 桜（さくら）の花（ ）たくさん 咲きました。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because the cherry blossoms (桜の花) are the intransitive subject that naturally performs the action of blooming (咲きました)!",wrongOptions:["を is completely wrong because '咲きます' (to bloom) is an intransitive verb and can never take a direct object with 'を'.","に is incorrect because the blossoms are the flowers themselves, not the point in time or location where things go.","で is wrong because 'で' would mean the flowers are acting as tools or venues, rather than being the items blooming."]}},
  {id:35,section:"A",level:"N5",question:"私は 毎朝 牛乳（ ）水を 飲みます。",options:["や","を","に","が"],correctIndex:0,explanations:{correct:"We use 'や' here because 'や' is used to link items in a non-exhaustive list, meaning 'things like milk and water' among others!",wrongOptions:["を is incorrect inside the blank because 'を' already appears after '水' to mark the whole group as objects; placing it here breaks grammar rules.","に is completely wrong because we are listing liquids to drink, not establishing destinations or numerical clock times.","が is wrong because the liquids are the objects being consumed, not the subject doing the drinking."]}},
  {id:36,section:"A",level:"N5",question:"デパートの 前（ ）ともだちに 会いました。",options:["で","に","を","へ"],correctIndex:1,explanations:{correct:"We use 'に' here because the verb '会います' (to meet) specifically takes the particle 'に' to mark the person or target location of meeting!",wrongOptions:["で is incorrect in standard beginner grammar tests because '会う' focuses heavily on the target interaction spot or person, preferring 'に'.","を is completely wrong because Japanese grammar strictly forbids using 'を' with the verb '会います'.","へ is wrong because 'へ' means direction towards a place, but here you are standing at the spot completing the meeting action."]}},
  {id:37,section:"A",level:"N5",question:"この部屋は ストーブが ありますから （ ）です。",options:["あったかい","さむい","あつい","すずしい"],correctIndex:0,explanations:{correct:"We use 'あったかい' (warm) because having a heater (ストーブ) turned on naturally makes a cold room comfortably warm!",wrongOptions:["さむい is completely wrong because 'さむい' means 'cold', which is the opposite of what a heater accomplishes.","あつい is incorrect because 'あつい' means uncomfortably hot or scorching, which is inappropriate for a standard cozy room heater description.","すずしい is wrong because 'すずしい' means 'cool/refreshing', which refers to autumn weather or nice breezes, not heater output."]}},
  {id:38,section:"A",level:"N5",question:"昨日は たくさん 歩きましたから、足が （ ）です。",options:["いたい","たかい","おもい","はやい"],correctIndex:0,explanations:{correct:"We use 'いたい' (painful/sore) because walking a massive amount yesterday would logically make your legs feel sore!",wrongOptions:["たかい is completely wrong because 'たかい' means expensive or tall, which cannot describe painful muscles.","おもい means 'heavy'; while legs can feel heavy, standard beginner test contexts focus on 'いたい' for physical exhaustion pain.","はやい is wrong because 'はやい' means fast or early, which doesn't describe the physical aftereffects of over-walking."]}},
  {id:39,section:"A",level:"N5",question:"あの 人は 口（くち）が （ ）人ですね。",options:["かるい","重い","大きい","おそい"],correctIndex:2,explanations:{correct:"We use '大きい' (big) here because '口が大きい' means someone has a big mouth (either literally or speaking loudly/frequently)!",wrongOptions:["かるい is incorrect because while '口が軽い' means someone can't keep secrets, '大きい' is the standard elementary spatial description taught at this level.","重い is wrong because '口が重い' means untalkative, which is rarely tested as a simple primary physical adjective combo without deep idioms.","おそい is completely wrong because 'おそい' means slow, and human mouths cannot be described as speed-slow on a basic level."]}},
  {id:40,section:"A",level:"N5",question:"この テーブルは 長（なが）（ ）ないです。",options:["く","で","に","だ"],correctIndex:0,explanations:{correct:"We use 'く' here because '長い' is an い-adjective, and its negative form requires replacing the final 'い' with 'くない'!",wrongOptions:["で is completely wrong because 'で' is exclusively used to make negative or connective states for nouns and な-adjectives.","に is incorrect because 'に' forms adverbs and cannot build the negative form 'ない' for an い-adjective.","だ is wrong because 'だ' is a declarative terminal word and cannot be injected into a negative adjective chain."]}},
  {id:41,section:"A",level:"N5",question:"駅（えき）の お手洗い（ ）どこですか。",options:["は","が","を","に"],correctIndex:0,explanations:{correct:"We use 'は' here because we are bringing up the restroom (お手洗い) as our main topic of conversation to ask where it is located!",wrongOptions:["が is less appropriate here because standard 'where is X' location inquiries naturally establish X as the known topic using 'は'.","を is completely wrong because asking where something is involves no active physical direct object manipulation.","に is wrong because 'に' would point to a destination, but we don't know where it is yet to label it a destination."]}},
  {id:42,section:"A",level:"N5",question:"私は カレー（ ）食べたいです。",options:["が","に","で","と"],correctIndex:0,explanations:{correct:"We use 'が' here because desire forms like '〜たい' (want to do) frequently use 'が' to mark the object of your intense desire!",wrongOptions:["に is completely wrong because curry is the food item you want to consume, not a destination or a point in time.","で is incorrect because curry is not the location or the tool you are using to eat another item.","と is wrong because 'と' means 'with', which would mean you want to sit down and share a meal side-by-side with a physical bowl of curry."]}},
  {id:43,section:"A",level:"N5",question:"山下さんは 英語（ ）話すことが できます。",options:["が","を","に","で"],correctIndex:1,explanations:{correct:"We use 'を' here because '話す' (to speak) is an active dictionary-form verb that naturally takes 'を' to mark the language being spoken!",wrongOptions:["が is incorrect here because the full potential phrase structure ends with 'ことが新しい/できます', meaning 'を' attaches directly to '話す'.","に is completely wrong because languages aren't time frames or geographic maps.","で is wrong because although you can speak *in* English (英語で), the grammar pattern 'verb-dictionary-form + ことができます' requires 'を' for standard objects."]}},
  {id:44,section:"A",level:"N5",question:"お姉さんは ピアノ（ ）弾く（ひく）ことが 上手です。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because '弾く' (to play a stringed instrument) is an active verb requiring 'を' to mark the musical instrument object!",wrongOptions:["が is incorrect here because 'が' appears later with '上手です'; the immediate verb '弾く' needs its direct object marked by 'を'.","に is completely wrong because a piano is a physical object, not a point in time or a travel location.","で is wrong because 'で' would mean playing an instrument by means of another tool, but the piano is the object being played."]}},
  {id:45,section:"A",level:"N5",question:"夏休み（ ）国へ 帰ります。",options:["に","で","を","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because '夏休み' (summer vacation) represents a specific block of time during which the action of returning occurs!",wrongOptions:["で is completely wrong because vacation is a time concept, not a physical room or tool where you perform actions.","を is incorrect because you cannot physically act upon or pick up summer vacation as a direct object.","へ is wrong because 'へ' means traveling towards a location, which is already correctly claimed by '国へ'."]}},
  {id:46,section:"A",level:"N5",question:"この川（かわ）（ ）泳いでは（およいでは）いけません。",options:["で","に","を","へ"],correctIndex:0,explanations:{correct:"We use 'で' here because swimming (泳ぐ) is an active physical exercise taking place within the spatial environment of the river!",wrongOptions:["に is incorrect because 'に' is for stationary objects or arrival targets, but swimming is an active, ongoing movement inside the water.","を is wrong here because you are actively swimming *inside* the river's body, rather than crossing over a boundary line.","へ is wrong because 'へ' means swimming toward the river from land, but the ban applies to the act of swimming inside it."]}},
  {id:47,section:"A",level:"N5",question:"一か月（ ）2回 映画を見ます。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because 'に' serves as the frequency marker per time unit (e.g., 'twice per month' = 一か月に2回)!",wrongOptions:["で is completely wrong because time periods do not act as physical tools or locations for frequency rates.","を is incorrect because time intervals cannot be the direct physical object of an action.","が is wrong because the frequency period is not the subject performing an active verb."]}},
  {id:48,section:"A",level:"N5",question:"あの人は 目（ ）大きいです。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because describing parts of the body (e.g., 'eyes are big') follows the standard pattern 'Topic + は + Body Part + が + Adjective'!",wrongOptions:["を is completely wrong because '大きい' is a descriptive adjective, not an action verb, so it can never take 'を'.","に is incorrect because human eyes are not spatial destinations or scheduled calendar times.","で is wrong because 'で' would mean 'by means of eyes', which does not make sense for a simple physical description."]}},
  {id:49,section:"A",level:"N5",question:"明日（あした）（ ）テニスを しませんか。",options:["に","は","を","で"],correctIndex:1,explanations:{correct:"We use 'は' here to highlight '明日' (tomorrow) as the main topic of our invitation, making the proposal smooth and clear!",wrongOptions:["に is completely wrong because relative time words like '明日' (tomorrow) never take the specific point-time particle 'に'.","を is incorrect because tomorrow is a time word, not a physical object that can be played or hit like a tennis ball.","で is wrong because tomorrow is a time concept, not a physical tennis court venue where games take place."]}},
  {id:50,section:"A",level:"N5",question:"こう茶（ちゃ）に 砂糖（さとう）（ ）入れます。",options:["を","に","で","が"],correctIndex:0,explanations:{correct:"We use 'を' here because '砂糖' (sugar) is the direct physical object that you are actively putting (入れます) into the tea!",wrongOptions:["に is incorrect inside this blank because 'こう茶に' already uses 'に' to show the destination; we can't label sugar as a destination.","で is completely wrong because sugar is the item being moved, not the physical room or tool doing the moving.","が is wrong because sugar isn't the autonomous person doing the action of putting things away."]}},
  {id:51,section:"B",level:"N5",question:"リーさんは 漢字を 書くこと（ ）おもしろいと言いました。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because '書くこと' (the act of writing) functions as the noun phrase subject that is being described by the adjective 'おもしろい'!",wrongOptions:["を is completely wrong because 'おもしろい' is a descriptive adjective, not an action verb, meaning it can never take a direct object with 'を'.","に is incorrect because the act of writing is neither a time coordinate nor a physical destination.","で is wrong because 'で' would imply that the act of writing is a physical location or tool used to do something else."]}},
  {id:52,section:"B",level:"N5",question:"寒いですから、窓（まど）（ ）閉めて（しめて）ください。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because '窓' (window) is the direct physical object that needs to receive the action of closing (閉めてください)!",wrongOptions:["が is incorrect here because '閉める' is a transitive action performed by a person, so the object being closed must take 'を'.","に is completely wrong because the window is not a destination you are traveling to or a numerical clock time.","で is wrong because the window is the target being shut, not the tool or place used to perform a separate action."]}},
  {id:53,section:"B",level:"N5",question:"鈴木さんは 来月（らいげつ）結婚（けっこん）（ ）します。",options:["を","に","で","が"],correctIndex:0,explanations:{correct:"We use 'を' here because '結婚' (marriage) combined with 'します' forms the transitive phrase 'to do/perform a marriage'!",wrongOptions:["に is completely wrong because marriage is an event/action noun here, not a destination or a point time like 3 o'clock.","で is incorrect because marriage is the action itself, not the physical wedding hall or venue where it takes place.","が is wrong because the subject getting married is Mr. Suzuki, not the abstract concept of marriage itself doing an action."]}},
  {id:54,section:"B",level:"N5",question:"お酒を 飲みすぎて、頭（あたま）（ ）痛いです。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because when describing a bodily state or condition with an adjective like '痛い' (painful), the body part takes 'が'!",wrongOptions:["を is completely wrong because '痛い' is a descriptive adjective, and adjectives can never take a direct object marked by 'を'.","に is incorrect because your head is the body part hurting, not a destination or a calendar time stamp.","で is wrong because your head is the subject experiencing the pain, not the physical tool used to create pain."]}},
  {id:55,section:"B",level:"N5",question:"この カバンは 軽くて（かるくて）便利（ ）です。",options:["だ","に","で","な"],correctIndex:2,explanations:{correct:"We use 'で' here because to link a な-adjective like '便利' (convenient) or a noun to 'です', the connective particle is 'で'!",wrongOptions:["だ is completely wrong because 'だ' is a casual ending and cannot be plugged mid-sentence right before 'です'.","に is incorrect because 'に' turns な-adjectives into adverbs, which doesn't fit a flat compound description.","な is wrong because 'な' is only used if a noun immediately follows '便利', but here it ends with the verb copula 'です'."]}},
  {id:56,section:"B",level:"N5",question:"昨日（きのう）の テストは あまり （ ）なかったです。",options:["むずかしく","むずかしい","むずかした","むずかしくで"],correctIndex:0,explanations:{correct:"We use 'むずかしく' because to put an い-adjective into the past negative form ('was not difficult'), we drop the 'い' and add 'くなかった'!",wrongOptions:["むずかしい is incorrect because it is the plain present tense form, which conflicts with 'yesterday' and 'なかった'.","むずかした is a completely broken non-existent conjugation that violates basic Japanese rules.","むずかしくで is wrong because adding 'で' inside a past negative adjective string is completely ungrammatical."]}},
  {id:57,section:"B",level:"N5",question:"あそこに いる 人（ ）だれですか。",options:["は","が","を","に"],correctIndex:0,explanations:{correct:"We use 'は' here because we are singling out 'the person over there' as our main topic of inquiry to ask who they are!",wrongOptions:["が is less ideal here because standard identity questions asking 'Who is X?' structure X as the established topic with 'は'.","を is completely wrong because asking someone's identity involves no direct physical action or object manipulation.","に is wrong because the person is the topic being identified, not a physical destination or a calendar time stamp."]}},
  {id:58,section:"B",level:"N5",question:"子ども（ ）公園（こうえん）で あそんでいます。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because the children (子ども) are the active subjects who are performing the action of playing!",wrongOptions:["を is completely wrong because playing (あそぶ) is an intransitive verb, so children cannot be the direct object of their own playing.","に is incorrect because children are living people, not spatial coordinates or numerical clock times.","で is wrong because 'で' marks the location of the action (which is already correctly marked by '公園で'), not the people playing."]}},
  {id:59,section:"B",level:"N5",question:"山田さんは 毎朝 新聞（しんぶん）（ ）読みます。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because '新聞' (newspaper) is the direct physical media object being actively read by the verb '読みます'!",wrongOptions:["が is incorrect because Mr. Yamada is the subject doing the reading, not the newspaper itself performing an action.","に is completely wrong because a newspaper is an object, not a travel destination or a specific time point.","で is wrong because 'で' would imply you are standing inside a newspaper or using it as a tool to read something else."]}},
  {id:60,section:"B",level:"N5",question:"お姉さんは 料理（ ）上手（じょうず）ではありません。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because ability words like '上手' (good at) and its negative '上手ではありません' always take 'が' to mark the skill field!",wrongOptions:["を is completely wrong because '上手' is a descriptive noun/adjective state, not an active verb, so it can never take 'を'.","に is incorrect because cooking is the skill category being discussed, not a travel destination or a clock time.","で is wrong because 'で' would mean 'by means of cooking', which fails to match the grammatical pattern for stating someone's skill level."]}},
  {id:61,section:"B",level:"N5",question:"日本（ ）食べ物は おいしいですが、高いです。",options:["の","に","で","が"],correctIndex:0,explanations:{correct:"We use 'の' here because 'の' links two nouns together, showing possession or origin ('Japan's food' / 'food of Japan')!",wrongOptions:["に is incorrect because 'に' would imply food existing inside Japan as a verb statement, but here it must directly modify the noun '食べ物'.","で is wrong because 'で' cannot directly link a country noun to another noun without a modifying verb clause.","が is completely wrong because 'が' would turn Japan into the subject that is delicious, instead of the food itself."]}},
  {id:62,section:"B",level:"N5",question:"私は 弟（おとうと）（ ）時計（とけい）を あげました。",options:["に","を","で","が"],correctIndex:0,explanations:{correct:"We use 'に' here because giving verbs like 'あげました' require 'に' to mark the recipient who receives the gift!",wrongOptions:["を is incorrect because '時計' (watch) is already the direct object being given, so the brother cannot take 'を'.","で is completely wrong because the brother is the person receiving the item, not the physical location or tool used to give it.","が is wrong because I am the subject giving the watch, not the younger brother doing the giving."]}},
  {id:63,section:"B",level:"N5",question:"木村さん（ ）英語で 手紙を書きました。",options:["は","を","に","で"],correctIndex:0,explanations:{correct:"We use 'は' here to establish Ms. Kimura as the primary topic of the sentence who performed the action of writing a letter!",wrongOptions:["を is completely wrong because Ms. Kimura is the human author of the letter, not the physical paper object being written upon.","に is incorrect because if she were the recipient, the sentence structure would require a separate subject instead of starting directly with her name.","で is wrong because Ms. Kimura is a living person, not a language tool or physical location where a letter is produced."]}},
  {id:64,section:"B",level:"N5",question:"この カフェ（ ）いつも コーヒーを 飲みます。",options:["で","に","を","へ"],correctIndex:0,explanations:{correct:"We use 'で' here because drinking coffee (コーヒーを飲む) is an active physical event taking place inside the cafe venue!",wrongOptions:["に is incorrect because 'に' is for simple stationary existence, whereas drinking coffee is a proactive lifestyle action requiring 'で'.","を is completely wrong because 'コーヒー' is already marked as the direct object, so the cafe cannot be the thing swallowed.","へ is wrong because 'へ' means traveling towards the cafe, but you are already inside sitting down and drinking."]}},
  {id:65,section:"B",level:"N5",question:"店（みせ）の 中（ ）たくさん 人が います。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because the existence verb 'います' (to exist for living things) requires 'に' to mark the location of existence!",wrongOptions:["で is incorrect because 'で' marks active events, but simply existing ('there are people') is a passive state, not an action.","を is completely wrong because 'います' is an intransitive verb and can never take a direct object with 'を'.","が is wrong because '人' (people) is already the subject marked by 'が', so we cannot label the inside of the shop with it."]}},
  {id:66,section:"B",level:"N5",question:"あの 赤い シャツ（ ）見せて ください。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because the red shirt (赤いシャツ) is the direct physical object you are requesting to see (見せてください)!",wrongOptions:["が is incorrect here because you are asking a clerk to show an item, making the shirt the target object of the request rather than the subject.","に is completely wrong because the shirt is not a travel destination or a numerical clock time.","で is wrong because the shirt is the item being looked at, not the tool or place used to perform a separate action."]}},
  {id:67,section:"B",level:"N5",question:"毎週 土曜日（ ）部屋（へや）の そうじを します。",options:["に","は","を","で"],correctIndex:0,explanations:{correct:"We use 'に' here because regular, specific calendar days like Saturday (土曜日) take 'に' to pinpoint when a routine action happens!",wrongOptions:["は is less accurate because we are stating a specific time coordinate for our cleaning schedule rather than creating a broad topic.","を is completely wrong because a calendar day cannot be the direct object of a cleaning action.","で is wrong because Saturday is a time concept, not the physical room or tool used to do the cleaning."]}},
  {id:68,section:"B",level:"N5",question:"私は 果物（くだもの）（ ）りんごが 一番 好きです。",options:["のなかで","に","を","から"],correctIndex:0,explanations:{correct:"We use 'のなかで' here because it means 'out of / among' a group, which is the standard grammar pattern for stating a top preference!",wrongOptions:["に is completely wrong because 'に' alone cannot express choosing a favorite item from a collective category of items.","を is incorrect because '好き' is an adjective and cannot take 'を', and it fails to establish the comparative category context.","から is wrong because 'から' means 'from', which would imply a strange journey starting out from inside a piece of fruit."]}},
  {id:69,section:"B",level:"N5",question:"あしたの 朝 8時（ ）駅で 会いましょう。",options:["に","で","を","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because 8 o'clock (8時) is an exact, numerical clock time point that requires 'に' to show the appointment time!",wrongOptions:["で is completely wrong because 'で' marks action locations, but 8:00 is a clock time, not a physical station platform building.","を is incorrect because clock times cannot be direct objects that receive an action.","へ is wrong because 'へ' indicates spatial direction, and you cannot physically travel inside the numbers of a clock."]}},
  {id:70,section:"B",level:"N5",question:"田中さんは 風邪（かぜ）（ ）学校を 休みました。",options:["で","に","を","が"],correctIndex:0,explanations:{correct:"We use 'で' here because 'で' is used to indicate the cause, reason, or ground for an event happening ('absent due to a cold')!",wrongOptions:["に is completely wrong because a cold is a medical illness state, not a travel destination or a specific time deadline.","を is incorrect because a cold is the reason for the absence, not a direct object being physically manipulated by the verb '休みました'.","が is wrong because '学校' is already the focus of the absence, and the cold didn't take a day off school by itself."]}},
  {id:71,section:"B",level:"N5",question:"日本語（ ）スピーチを しました。",options:["で","に","を","が"],correctIndex:0,explanations:{correct:"We use 'で' here because 'で' marks the language medium or tool used to deliver the active speech ('in Japanese')!",wrongOptions:["に is completely wrong because a language is not a physical destination or a scheduled clock time.","を is incorrect because 'スピーチ' (speech) is already the direct object receiving 'しました', so we cannot use 'を' twice here.","が is wrong because Japanese language is the tool used, not the active person standing on stage delivering the speech."]}},
  {id:72,section:"B",level:"N5",question:"冷たい 水（ ）飲みたいです。",options:["が","に","で","へ"],correctIndex:0,explanations:{correct:"We use 'が' here because standard desire forms using '〜たい' (want to drink) naturally use 'が' to highlight the object of desire!",wrongOptions:["に is completely wrong because cold water is a beverage to swallow, not a geographic destination or a clock time point.","で is incorrect because water is the item being consumed, not the physical tool or room used to perform a separate action.","へ is wrong because 'へ' shows direction towards a place, and you cannot travel towards a glass of water like a city."]}},
  {id:73,section:"B",level:"N5",question:"この 花は いい におい（ ）します。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because sensory expressions describing smells, sounds, or tastes use the standard set phrase pattern 'Noun + がする'!",wrongOptions:["を is incorrect because the flower is emitting a scent naturally, and sensory perceptions use 'がする' rather than an active 'を' choice.","に is completely wrong because a smell is a sensory experience, not a travel destination or clock time.","で is wrong because the scent is the output being noticed, not the tool or location where another event happens."]}},
  {id:74,section:"B",level:"N5",question:"帽子（ぼうし）（ ）かぶって 出かけます。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because '帽子' (hat) is the direct physical object being put on your head by the clothing verb 'かぶる'!",wrongOptions:["が is incorrect here because you are the subject performing the action of wearing the hat, so the hat must be marked as the object.","に is completely wrong because a hat is an article of clothing, not a location destination or calendar time stamp.","で is wrong because the hat is the item being worn, not the location or separate tool used to perform an errand."]}},
  {id:75,section:"B",level:"N5",question:"あした、先生の 家（ ）伺います（うかがいます）。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because '伺います' (humble form of to visit/go) requires 'に' to mark the destination house you are visiting!",wrongOptions:["で is incorrect because 'で' marks where an action happens, but here we are traveling *to* the house as our endpoint destination.","を is completely wrong because a house is a destination target, not a direct object you can physically lift or grab.","が is wrong because the house isn't the subject doing any visiting; the speaker is the one traveling."]}},
  {id:76,section:"B",level:"N5",question:"鈴木さんは 車（ ）運転（うんてん）が できません。",options:["の","を","に","で"],correctIndex:0,explanations:{correct:"We use 'の' here because it forms the noun phrase '車の運転' (car driving / the driving of cars), connecting the two nouns smoothly!",wrongOptions:["を is incorrect inside this blank because '運転' is a noun here followed by 'ができません'; you cannot place 'を' directly between two linked nouns like this.","に is completely wrong because a car is an object, not a destination or a specific time coordinate.","で is wrong because 'で' would mean doing an action by means of a car, but here we are describing the overall skill of car-driving."]}},
  {id:77,section:"B",level:"N5",question:"木村さんは テニス（ ）ピンポンも 好きです。",options:["や","を","に","で"],correctIndex:0,explanations:{correct:"We use 'や' here because 'や' links nouns in a non-exhaustive list, meaning 'things like tennis and also ping pong'!",wrongOptions:["を is completely wrong because '好き' is an adjective and cannot take 'を', and using it here would break basic noun-linking rules.","に is incorrect because sports are hobbies, not geographic travel destinations or numerical clock times.","で is wrong because 'で' would mean using tennis as a tool or location, which does not fit a simple list of favorite sports."]}},
  {id:78,section:"B",level:"N5",question:"私の 部屋には 机（ ）いすが あります。",options:["と","を","に","で"],correctIndex:0,explanations:{correct:"We use 'と' here because 'と' is the complete listing particle used to join nouns together when you mean 'and' explicitly!",wrongOptions:["を is completely wrong because 'あります' is an intransitive existence verb and can never take a direct object with 'を'.","に is incorrect because furniture items are things that exist, not the location or time stamp where things are located.","で is wrong because 'で' would mean the desk is a physical venue where the chair is actively performing a task."]}},
  {id:79,section:"B",level:"N5",question:"ここから 学校まで 自転車（ ）10分です。",options:["で","に","を","が"],correctIndex:0,explanations:{correct:"We use 'で' here because a bicycle (自転車) is the physical transport tool and vehicle method used to achieve the trip!",wrongOptions:["に is completely wrong because 'に' would mean arriving inside the bicycle as a destination, rather than riding it to school.","を is incorrect because you are not manipulating or acting upon the bicycle as a direct object in this clause.","が is wrong because the bicycle isn't the subject performing an active verb; it is simply the method of transit."]}},
  {id:80,section:"B",level:"N5",question:"お父さんは 毎朝 新聞を 読み（ ）会社へ行きます。",options:["ながら","て","に","で"],correctIndex:1,explanations:{correct:"We use 'て' (te-form connecting sequential actions) — the te-form '読んで' links sequential events: first reading the paper, then going to work!",wrongOptions:["ながら is incorrect because '読みながら' means doing both simultaneously, but you cannot safely read a newspaper while physically traveling to an office building.","に is completely wrong because 'に' would mean reading is a destination, which makes no grammatical sense.","で is wrong because 'で' cannot attach directly to a verb dictionary or stem form to show sequential life actions."]}},
  {id:81,section:"B",level:"N5",question:"私の 趣味（しゅみ）は 写真を 撮る（とる）こと（ ）です。",options:["だ","に","で","な"],correctIndex:2,explanations:{correct:"We use 'で' here as part of '〜ことで' linking the hobby noun to what follows, or functioning as the connective before 'です' in extended sentence structures!",wrongOptions:["だ is incorrect because 'こと' acts as a noun directly before the sentence final copula structure, making an extra middle 'だ' redundant.","に is completely wrong because a hobby definition is an identity statement, not a geographic destination or clock time.","な is wrong because 'な' is only for linking な-adjectives to nouns, but 'こと' is already a noun concluding the thought."]}},
  {id:82,section:"B",level:"N5",question:"教室（きょうしつ）の ドア（ ）開けて ください。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because the door (ドア) is the direct physical object receiving the manual action of opening (開けてください)!",wrongOptions:["が is incorrect here because you are instructing someone to open the door, making the door the object of the action, not the subject doing the opening.","に is completely wrong because a door is an object, not a travel destination or a specific time on a clock.","で is wrong because the door is the item being moved, not the physical room or tool used to perform a separate action."]}},
  {id:83,section:"B",level:"N5",question:"あの レストランは 料理が おいしい（ ）有名です。",options:["くて","で","に","だ"],correctIndex:1,explanations:{correct:"We use 'で' here because 'で' is used after a completed clause or noun concept to show the reason or cause for being famous ('famous for...')!",wrongOptions:["くて is incorrect because 'おいしいくて' is a grammatical error; you can link adjectives with 'くて' but it doesn't express the clear cause for fame like 'で'.","に is completely wrong because fame reasons are not geographic destinations or clock deadlines.","だ is wrong because 'だ' is a casual sentence closer and cannot act as a connective particle showing cause mid-sentence."]}},
  {id:84,section:"B",level:"N5",question:"私は 日本の アニメ（ ）興味（きょうみ）が あります。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because the standard grammatical phrase for having an interest in something is '〜に興味がある'!",wrongOptions:["で is incorrect because 'で' shows location of action, but having an interest is a state directed at a target, requiring 'に'.","を is completely wrong because 'あります' is an intransitive verb and can never take a direct object with 'を'.","が is wrong because '興味' (interest) is already the subject marked by 'が', so we cannot use 'が' twice on the topic."]}},
  {id:85,section:"B",level:"N5",question:"この ズボンは 少し 長（なが）（ ）ないですか。",options:["く","で","に","だ"],correctIndex:0,explanations:{correct:"We use 'く' here because '長い' is an い-adjective, and its question negative form ('isn't it long?') requires changing 'い' to 'く' before 'ない'!",wrongOptions:["で is completely wrong because 'で' is exclusively used for nouns and な-adjectives, never for い-adjectives.","に is incorrect because 'に' forms adverbs and cannot build a negative description with 'ない'.","だ is wrong because 'だ' is a plain copula and cannot be inserted into the middle of an adjective conjugation."]}},
  {id:86,section:"B",level:"N5",question:"おなかが 痛いですから、病院（びょういん）（ ）行きます。",options:["へ","を","で","が"],correctIndex:0,explanations:{correct:"We use 'へ' here because it cleanly and accurately marks the spatial direction and destination toward which you are traveling (the hospital)!",wrongOptions:["を is completely wrong because a hospital is a physical location you go to, not a direct object you can pick up or eat.","で is incorrect because 'で' would mean you are already inside the hospital performing an action, but you are currently traveling there.","が is wrong because you are the subject going to the hospital, not the hospital building traveling somewhere else."]}},
  {id:87,section:"B",level:"N5",question:"会社（かいしゃ）（ ）遅れないで（おくれないで）ください。",options:["に","を","で","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because the verb '遅れる' (to be late) natively takes the particle 'に' to mark the specific target event or location you are late for!",wrongOptions:["を is completely wrong because being late is an intransitive state, so it cannot take a direct physical object with 'を'.","で is incorrect because 'で' marks where an action happens, but 'に' is the mandatory grammatical match for the target of lateness.","へ is wrong because 'へ' implies traveling towards a destination, but the phrase focuses on the deadline meeting point."]}},
  {id:88,section:"B",level:"N5",question:"天気が いいですから、外（そと）（ ）遊びましょう。",options:["で","に","を","へ"],correctIndex:0,explanations:{correct:"We use 'で' here because playing outside (遊びましょう) is an active physical pastime taking place within that specific venue spatial area!",wrongOptions:["に is incorrect because playing is a dynamic active verb, which requires the action location particle 'で' rather than static 'に'.","を is completely wrong because playing is an intransitive verb, so the outside space cannot be a direct object.","へ is wrong because you are going to actively hang out and play outside, not just walk in its direction."]}},
  {id:89,section:"B",level:"N5",question:"お父さんは 毎朝 コーヒー（ ）飲みます。",options:["を","が","に","で"],correctIndex:0,explanations:{correct:"We use 'を' here because 'コーヒー' (coffee) is the direct physical liquid being consumed by the active verb '飲みます'!",wrongOptions:["が is incorrect here because the father is the main subject drinking, not the coffee itself performing an action.","に is completely wrong because coffee is a beverage, not a travel destination or a numerical clock time point.","で is wrong because 'で' would mean using coffee as a tool or room to perform a separate action."]}},
  {id:90,section:"B",level:"N5",question:"私は いつも 夜 11時（ ）寝ます。",options:["に","で","を","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because 11:00 PM (11時) is an exact, specific numerical clock time that requires 'に' to show when the action happens!",wrongOptions:["で is completely wrong because clock times are not physical locations or tools where actions take place.","を is incorrect because a clock time cannot be a direct physical object that you can manipulate.","へ is wrong because 'へ' indicates direction, and you cannot physically travel toward a number on a clock."]}},
  {id:91,section:"B",level:"N5",question:"お母さんは デパート（ ）買い物を しました。",options:["で","に","を","へ"],correctIndex:0,explanations:{correct:"We use 'で' here because shopping (買い物をした) is an active commercial event taking place inside the department store building!",wrongOptions:["に is incorrect because 'に' implies static existence, but shopping is a dynamic, multi-step action requiring 'で'.","を is completely wrong because '買い物' is already the object of the verb clause, so the department store cannot take 'を'.","へ is wrong because mom already completed the shopping event inside, rather than just traveling in its direction."]}},
  {id:92,section:"B",level:"N5",question:"この 図書館（としょかん）は 静か（ ）きれいです。",options:["で","に","な","だ"],correctIndex:0,explanations:{correct:"We use 'で' here because to link a な-adjective like '静か' (quiet) to another descriptive adjective, we use the connective form 'で'!",wrongOptions:["に is incorrect because 'に' turns な-adjectives into adverbs, which doesn't fit a flat compound list of descriptions.","な is wrong because 'な' is only used if a noun directly follows immediately after '静か', but here another adjective follows.","だ is wrong because 'だ' terminates a casual sentence and cannot cleanly link descriptions mid-sentence."]}},
  {id:93,section:"B",level:"N5",question:"私は まだ 漢字を 100文字（ ）書けません。",options:["しか","だけ","ごろ","まで"],correctIndex:0,explanations:{correct:"We use 'しか' here because 'しか' means 'only' when paired with a negative verb ('書けません'), highlighting a restrictive limit!",wrongOptions:["だけ also means 'only', but it is paired with positive verbs, making it grammatically incorrect before '書けません' in this specific testing context.","ごろ is completely wrong because 'ごろ' is exclusively used for approximate clock times, never for counting quantities of kanji.","まで is wrong because 'まで' means 'until', which does not make sense right before a negative potential verb form."]}},
  {id:94,section:"B",level:"N5",question:"お姉さんは 歌を 歌うこと（ ）上手です。",options:["が","を","に","で"],correctIndex:0,explanations:{correct:"We use 'が' here because skill adjectives like '上手' (good at) always take the particle 'が' to mark the specific field of talent!",wrongOptions:["を is completely wrong because '上手' is an adjective description, not an active verb, so it can never take 'を'.","に is incorrect because the hobby activity is the focus of talent, not a travel destination or clock deadline.","で is wrong because 'で' fails to complete the standard required grammatical pattern for expressing personal skill levels."]}},
  {id:95,section:"B",level:"N5",question:"木村さんは 来週（らいしゅう）東京（ ）行きます。",options:["へ","を","で","が"],correctIndex:0,explanations:{correct:"We use 'へ' here because Tokyo is the clear geographic destination and travel direction toward which she is moving!",wrongOptions:["を is completely wrong because Tokyo is a city location, not a physical object you can grab or eat.","で is incorrect because 'で' would mean she is performing an action inside Tokyo, but she is currently in the process of traveling there.","が is wrong because Ms. Kimura is the subject traveling, not the city of Tokyo itself moving around."]}},
  {id:96,section:"B",level:"N5",question:"あのビル（ ）エレベーターが ありません。",options:["に","で","を","が"],correctIndex:0,explanations:{correct:"We use 'に' here because the existence phrase 'ありません' (does not exist) requires 'に' to point out the location of non-existence!",wrongOptions:["で is incorrect because 'で' marks active event venues, but a building lacking an elevator is a static state, not an action.","を is completely wrong because 'ありません' is an intransitive verb and can never take a direct object with 'を'.","が is wrong because 'エレベーター' is already the subject marked by 'が', so we cannot label the building location with it."]}},
  {id:97,section:"B",level:"N5",question:"毎日 お風呂（おふろ）（ ）入ります（はいります）。",options:["に","を","で","へ"],correctIndex:0,explanations:{correct:"We use 'に' here because entering a space (お風呂に入る) always takes 'に' to mark the destination space you are stepping into!",wrongOptions:["を is incorrect because '入る' is an intransitive motion verb focusing on the entry point, which takes 'に' instead of 'を'.","で is wrong because 'で' would mean you are performing a separate action inside the tub, but the phrase focuses on the act of getting inside.","へ is less ideal because standard everyday set phrases for taking a bath strictly mandate 'お風呂に入る' with 'に'."]}},
  {id:98,section:"B",level:"N5",question:"昨日（きのう）は 晩ご飯を 食べ（ ）寝ました。",options:["ないで","ず","なくて","ないに"],correctIndex:0,explanations:{correct:"We use 'ないで' here because the grammar pattern '〜ないで' means 'without doing X', perfectly fitting 'went to sleep without eating dinner'!",wrongOptions:["ず is too advanced/formal and typically requires a different archaic structure variation not taught at the absolute beginner level.","なくて is used for joining negative descriptions or showing causes, not for expressing 'without performing an action' before a main verb.","ないに is a completely made-up non-existent grammar structure that breaks basic Japanese rules."]}},
  {id:99,section:"C",level:"N4",question:"マリアさんは 日本へ 来た（ ）ばかりです。",options:["ところ","とき","こと","もの"],correctIndex:0,explanations:{correct:"We use 'ところ' here because 'たところ' followed by 'ばかり' or used on its own conveys the nuance of 'just arrived' — something that has just happened very recently!",wrongOptions:["とき means 'when', which would require a trailing clause rather than cleanly ending a sentence structure with 'です' here.","こと nominalizes actions into absolute facts but does not convey the recent immediate timeline aspect needed here.","もの refers to physical tangible objects, which makes absolutely no sense when describing the timeline of arriving in a country."]}},
  {id:100,section:"C",level:"N4",question:"田中さんは 毎日 走って（ ）ので、とても 元気（げんき）です。",options:["いる","ある","おく","みる"],correctIndex:0,explanations:{correct:"We use 'いる' here because the continuous state form '〜ている' indicates a regular ongoing daily habit ('keeps on running every day')!",wrongOptions:["ある is completely wrong because '〜てある' is exclusively used for inanimate objects and results of deliberate actions, never for human exercise habits.","おく means 'to do something in advance', which does not fit the context of describing why someone is currently super healthy.","みる means 'to try doing something to see how it turns out', which completely fails to express a long-term daily fitness habit."]}}
];

const CHEAT_SHEET = [
  { particle: "に", uses: ["Location of existence (あります・います)", "Specific time (clock times, days of week)", "Destination of motion (行く・来る)", "Recipient of giving verbs (あげる)", "Target of verbs (会う・遅れる)", "Frequency marker (一か月に2回)", "な-adj → adverb (静かに)"] },
  { particle: "で", uses: ["Location of action (active verbs)", "Tool / means / vehicle", "Language medium (日本語で)", "Material (木で作る)", "Cause / reason (風邪で)", "Connecting な-adj (静かで)", "Unit / cost basis (100円で)"] },
  { particle: "を", uses: ["Direct object of transitive verbs", "Path of motion verbs (歩く・走る)", "Space you move through (さんぽする)", "Clothing verbs (かぶる・着る)"] },
  { particle: "が", uses: ["Subject of existence (あります・います)", "Subject of intransitive verbs", "Object of desire (〜たい)", "Object of potential (わかる・できる)", "Body part descriptions (目が大きい)", "Skill marker with 上手・下手", "Sensory phrases (においがする)"] },
  { particle: "へ", uses: ["Direction toward a destination", "Travel destination (softer than に)"] },
  { particle: "は", uses: ["Topic marker (establishes main topic)", "Contrast marker", "Time words as topic (今日は)", "Question topics (お手洗いは?)"] },
  { particle: "と", uses: ["Doing together with someone", "Complete list (A and B, exhaustive)", "Quoting / thinking (と言う・と思う)"] },
  { particle: "や", uses: ["Non-exhaustive list (A and B, among others)"] },
  { particle: "の", uses: ["Possession / noun modification (日本の食べ物)", "Nominalizer (のが好き)", "Noun linking (車の運転)"] },
];

const PASTEL = {
  bg: "#FFF0F5",
  card: "#FFFFFF",
  primary: "#E8709A",
  primaryLight: "#F9B8D0",
  primaryDark: "#C04E78",
  accent: "#A8D8B9",
  accentDark: "#5D9E7A",
  wrong: "#FFE0E0",
  wrongBorder: "#F4A0A0",
  wrongText: "#C04040",
  correct: "#E0F8EC",
  correctBorder: "#80D4A8",
  correctText: "#2E7D5A",
  text: "#3D1A2E",
  textMuted: "#9E6882",
  sectionA: "#FFD6E8",
  sectionB: "#D6E8FF",
  sectionC: "#D6FFE8",
};

export default function App() {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selected, setSelected] = useState(null);
  const [score, setScore] = useState(0);
  const [showSheet, setShowSheet] = useState(false);
  const [finished, setFinished] = useState(false);
  const [wrongIndexes, setWrongIndexes] = useState([]);
  const [reviewMode, setReviewMode] = useState(false);
  const [reviewIdx, setReviewIdx] = useState(0);
  const sheetRef = useRef(null);

  const q = reviewMode ? QUESTIONS[wrongIndexes[reviewIdx]] : QUESTIONS[currentIdx];
  const total = QUESTIONS.length;
  const progress = reviewMode ? ((reviewIdx + 1) / wrongIndexes.length) * 100 : ((currentIdx + 1) / total) * 100;

  function handleSelect(i) {
    if (selected !== null) return;
    setSelected(i);
    if (i === q.correctIndex) setScore(s => s + 1);
    else setWrongIndexes(w => [...w, reviewMode ? wrongIndexes[reviewIdx] : currentIdx]);
  }

  function handleNext() {
    if (reviewMode) {
      if (reviewIdx + 1 >= wrongIndexes.length) { setFinished(true); }
      else setReviewIdx(r => r + 1);
    } else {
      if (currentIdx + 1 >= total) setFinished(true);
      else setCurrentIdx(c => c + 1);
    }
    setSelected(null);
  }

  function restart() {
    setCurrentIdx(0); setSelected(null); setScore(0);
    setFinished(false); setWrongIndexes([]); setReviewMode(false); setReviewIdx(0);
  }

  function startReview() {
    setReviewIdx(0); setSelected(null); setReviewMode(true); setFinished(false);
    setWrongIndexes(prev => [...new Set(prev)]);
  }

  const sectionColor = { A: PASTEL.sectionA, B: PASTEL.sectionB, C: PASTEL.sectionC };

  const styles = {
    app: { minHeight: "100vh", background: `linear-gradient(135deg, #FFF0F5 0%, #FDE8F2 50%, #F0E8FF 100%)`, fontFamily: "'Segoe UI', system-ui, sans-serif", padding: "0 0 40px" },
    header: { background: "rgba(255,255,255,0.85)", backdropFilter: "blur(12px)", borderBottom: `2px solid ${PASTEL.primaryLight}`, padding: "16px 24px", display: "flex", justifyContent: "space-between", alignItems: "center", position: "sticky", top: 0, zIndex: 100 },
    logo: { display: "flex", alignItems: "center", gap: 10 },
    logoText: { fontSize: 20, fontWeight: 700, color: PASTEL.primaryDark, letterSpacing: "-0.3px" },
    logoSub: { fontSize: 12, color: PASTEL.textMuted, marginTop: -2 },
    scoreChip: { background: PASTEL.primaryLight, color: PASTEL.primaryDark, padding: "6px 14px", borderRadius: 20, fontSize: 14, fontWeight: 600 },
    sheetBtn: { background: PASTEL.primary, color: "#fff", border: "none", borderRadius: 20, padding: "7px 16px", fontSize: 13, fontWeight: 600, cursor: "pointer", display: "flex", alignItems: "center", gap: 6 },
    main: { maxWidth: 680, margin: "0 auto", padding: "24px 16px" },
    progressWrap: { marginBottom: 20 },
    progressInfo: { display: "flex", justifyContent: "space-between", fontSize: 13, color: PASTEL.textMuted, marginBottom: 6 },
    progressBar: { height: 8, background: PASTEL.primaryLight, borderRadius: 8, overflow: "hidden" },
    progressFill: { height: "100%", background: `linear-gradient(90deg, ${PASTEL.primary}, ${PASTEL.primaryDark})`, borderRadius: 8, transition: "width 0.5s ease" },
    card: { background: "#fff", borderRadius: 24, padding: "28px 28px 24px", boxShadow: "0 4px 24px rgba(200,80,130,0.10)", border: `1.5px solid ${PASTEL.primaryLight}`, marginBottom: 16 },
    sectionBadge: (s) => ({ display: "inline-block", background: sectionColor[s] || "#eee", color: PASTEL.primaryDark, padding: "3px 12px", borderRadius: 20, fontSize: 12, fontWeight: 700, marginBottom: 12 }),
    question: { fontSize: 22, color: PASTEL.text, lineHeight: 1.5, marginBottom: 24, fontWeight: 500 },
    optionBtn: (state) => {
      const base = { width: "100%", textAlign: "left", padding: "14px 18px", borderRadius: 14, fontSize: 16, marginBottom: 10, cursor: state === "idle" ? "pointer" : "default", fontWeight: 500, border: "2px solid", transition: "all 0.2s", display: "flex", alignItems: "center", gap: 12 };
      if (state === "correct") return { ...base, background: PASTEL.correct, borderColor: PASTEL.correctBorder, color: PASTEL.correctText };
      if (state === "wrong") return { ...base, background: PASTEL.wrong, borderColor: PASTEL.wrongBorder, color: PASTEL.wrongText };
      if (state === "idle") return { ...base, background: "#FFF8FC", borderColor: PASTEL.primaryLight, color: PASTEL.text };
      return { ...base, background: "#F8F8F8", borderColor: "#E8E8E8", color: "#AAA" };
    },
    optionTag: (state) => ({ width: 28, height: 28, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 700, flexShrink: 0, background: state === "correct" ? PASTEL.correctBorder : state === "wrong" ? PASTEL.wrongBorder : PASTEL.primaryLight, color: state === "correct" ? PASTEL.correctText : state === "wrong" ? PASTEL.wrongText : PASTEL.primaryDark }),
    breakdownCard: { background: "linear-gradient(135deg, #FFF0F8, #F8F0FF)", borderRadius: 18, padding: "20px 22px", border: `1.5px solid ${PASTEL.primaryLight}`, marginTop: 4 },
    breakdownTitle: { fontSize: 13, fontWeight: 700, color: PASTEL.primaryDark, marginBottom: 10, textTransform: "uppercase", letterSpacing: 1 },
    correctExplain: { background: PASTEL.correct, borderRadius: 12, padding: "12px 14px", marginBottom: 10, fontSize: 14, color: PASTEL.correctText, lineHeight: 1.6 },
    wrongExplain: (i) => ({ background: i % 2 === 0 ? "#FFF5F5" : "#FFF9F0", borderRadius: 12, padding: "10px 14px", marginBottom: 8, fontSize: 13, color: "#666", lineHeight: 1.6 }),
    nextBtn: { width: "100%", background: `linear-gradient(135deg, ${PASTEL.primary}, ${PASTEL.primaryDark})`, color: "#fff", border: "none", borderRadius: 16, padding: "14px", fontSize: 16, fontWeight: 700, cursor: "pointer", marginTop: 8, letterSpacing: 0.3 },
    finishCard: { background: "#fff", borderRadius: 24, padding: "40px 28px", textAlign: "center", boxShadow: "0 4px 24px rgba(200,80,130,0.12)", border: `1.5px solid ${PASTEL.primaryLight}` },
    finishScore: { fontSize: 64, fontWeight: 800, color: PASTEL.primary, lineHeight: 1 },
    finishLabel: { fontSize: 16, color: PASTEL.textMuted, marginTop: 4, marginBottom: 20 },
    finishBtns: { display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" },
    reviewBtn: { background: PASTEL.primaryLight, color: PASTEL.primaryDark, border: "none", borderRadius: 14, padding: "12px 24px", fontSize: 15, fontWeight: 700, cursor: "pointer" },
    restartBtn: { background: `linear-gradient(135deg, ${PASTEL.primary}, ${PASTEL.primaryDark})`, color: "#fff", border: "none", borderRadius: 14, padding: "12px 24px", fontSize: 15, fontWeight: 700, cursor: "pointer" },
    overlay: { position: "fixed", inset: 0, background: "rgba(60,20,45,0.35)", zIndex: 200, display: "flex", justifyContent: "flex-end" },
    sheetPanel: { width: 340, maxWidth: "90vw", background: "#fff", height: "100vh", overflowY: "auto", boxShadow: "-4px 0 32px rgba(200,80,130,0.18)", padding: "24px 20px" },
    sheetHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
    sheetTitle: { fontSize: 18, fontWeight: 800, color: PASTEL.primaryDark },
    closeBtn: { background: PASTEL.primaryLight, border: "none", borderRadius: 10, padding: "6px 12px", cursor: "pointer", color: PASTEL.primaryDark, fontWeight: 700, fontSize: 14 },
    particleBlock: { marginBottom: 18, background: "#FFF8FC", borderRadius: 14, padding: "14px 16px", border: `1px solid ${PASTEL.primaryLight}` },
    particleLabel: { fontSize: 28, fontWeight: 800, color: PASTEL.primary, marginBottom: 8 },
    useItem: { fontSize: 13, color: PASTEL.text, lineHeight: 1.8, paddingLeft: 4, borderLeft: `3px solid ${PASTEL.primaryLight}`, paddingLeft: 8, marginBottom: 4 },
    welcomeBanner: { background: `linear-gradient(135deg, ${PASTEL.primary}, ${PASTEL.primaryDark})`, color: "#fff", borderRadius: 20, padding: "18px 24px", marginBottom: 20, display: "flex", justifyContent: "space-between", alignItems: "center" },
    welcomeText: { fontSize: 15 },
    welcomeName: { fontSize: 22, fontWeight: 800, letterSpacing: "-0.3px" },
  };

  function getOptionState(i) {
    if (selected === null) return "idle";
    if (i === q.correctIndex) return "correct";
    if (i === selected && i !== q.correctIndex) return "wrong";
    return "dim";
  }

  const labels = ["A", "B", "C", "D"];

  if (finished && !reviewMode) {
    const pct = Math.round((score / total) * 100);
    const medal = pct >= 90 ? "🌸" : pct >= 70 ? "🌷" : pct >= 50 ? "🌼" : "🌱";
    return (
      <div style={styles.app}>
        <div style={styles.header}>
          <div style={styles.logo}>
            <div>
              <div style={styles.logoText}>さるじゃの 日本語</div>
              <div style={styles.logoSub}>Saruja's Japanese Quiz</div>
            </div>
          </div>
        </div>
        <div style={styles.main}>
          <div style={styles.finishCard}>
            <div style={{ fontSize: 56, marginBottom: 12 }}>{medal}</div>
            <div style={styles.finishScore}>{score}/{total}</div>
            <div style={styles.finishLabel}>{pct}% correct · {pct >= 80 ? "Excellent work, Saruja!" : pct >= 60 ? "Good effort, keep going!" : "Keep practicing, you've got this!"}</div>
            <div style={{ fontSize: 14, color: PASTEL.textMuted, marginBottom: 24 }}>Wrong answers: {[...new Set(wrongIndexes)].length} questions to review</div>
            <div style={styles.finishBtns}>
              {wrongIndexes.length > 0 && <button style={styles.reviewBtn} onClick={startReview}>Review Wrong Answers 🔁</button>}
              <button style={styles.restartBtn} onClick={restart}>Start Over 🌸</button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (finished && reviewMode) {
    return (
      <div style={styles.app}>
        <div style={styles.header}><div style={styles.logo}><div><div style={styles.logoText}>さるじゃの 日本語</div></div></div></div>
        <div style={styles.main}>
          <div style={styles.finishCard}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>✨</div>
            <div style={{ fontSize: 26, fontWeight: 800, color: PASTEL.primaryDark, marginBottom: 8 }}>Review Complete!</div>
            <div style={styles.finishLabel}>Great job going through all the tricky ones, Saruja!</div>
            <div style={styles.finishBtns}>
              <button style={styles.restartBtn} onClick={restart}>Start Over 🌸</button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.app}>
      <div style={styles.header}>
        <div style={styles.logo}>
          <div>
            <div style={styles.logoText}>さるじゃの 日本語</div>
            <div style={styles.logoSub}>Saruja's Japanese Quiz — {reviewMode ? "Review Mode" : `${QUESTIONS[currentIdx].level} · Section ${QUESTIONS[currentIdx].section}`}</div>
          </div>
        </div>
        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          <div style={styles.scoreChip}>🌸 {score} pts</div>
          <button style={styles.sheetBtn} onClick={() => setShowSheet(true)}>📋 Cheat Sheet</button>
        </div>
      </div>

      <div style={styles.main}>
        {currentIdx === 0 && !reviewMode && (
          <div style={styles.welcomeBanner}>
            <div>
              <div style={styles.welcomeText}>Welcome back,</div>
              <div style={styles.welcomeName}>Saruja! 🌸</div>
              <div style={{ fontSize: 13, opacity: 0.85, marginTop: 4 }}>100 questions · MEXT Japanese Exam Prep</div>
            </div>
            <div style={{ fontSize: 40 }}>がんばって！</div>
          </div>
        )}

        {reviewMode && (
          <div style={{ background: "#FFF0D0", borderRadius: 16, padding: "12px 18px", marginBottom: 16, fontSize: 14, color: "#9E6020", fontWeight: 600, border: "1.5px solid #FFCF80" }}>
            🔁 Review Mode — Question {reviewIdx + 1} of {wrongIndexes.length} missed questions
          </div>
        )}

        <div style={styles.progressWrap}>
          <div style={styles.progressInfo}>
            <span>Question {reviewMode ? reviewIdx + 1 : currentIdx + 1} of {reviewMode ? wrongIndexes.length : total}</span>
            <span>{Math.round(progress)}%</span>
          </div>
          <div style={styles.progressBar}>
            <div style={{ ...styles.progressFill, width: `${progress}%` }} />
          </div>
        </div>

        <div style={styles.card}>
          <span style={styles.sectionBadge(q.section)}>Section {q.section} · {q.level}</span>
          <div style={styles.question}>{q.question}</div>

          {q.options.map((opt, i) => {
            const state = getOptionState(i);
            return (
              <button key={i} style={styles.optionBtn(state)} onClick={() => handleSelect(i)}>
                <span style={styles.optionTag(state)}>{labels[i]}</span>
                <span style={{ fontSize: 18 }}>{opt}</span>
                {state === "correct" && <span style={{ marginLeft: "auto" }}>✓</span>}
                {state === "wrong" && <span style={{ marginLeft: "auto" }}>✗</span>}
              </button>
            );
          })}

          {selected !== null && (
            <div style={styles.breakdownCard}>
              <div style={styles.breakdownTitle}>Why? ✨</div>
              <div style={styles.correctExplain}>
                <strong>✓ Correct answer:</strong> {q.explanations.correct}
              </div>
              {q.options.map((opt, i) => {
                if (i === q.correctIndex) return null;
                const wrongIdx = i < q.correctIndex ? i : i - 1;
                const explanation = q.explanations.wrongOptions[wrongIdx] || q.explanations.wrongOptions[i];
                return (
                  <div key={i} style={styles.wrongExplain(i)}>
                    <strong style={{ color: PASTEL.wrongText }}>✗ {opt}:</strong> {explanation}
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {selected !== null && (
          <button style={styles.nextBtn} onClick={handleNext}>
            {(reviewMode ? reviewIdx + 1 >= wrongIndexes.length : currentIdx + 1 >= total) ? "See Results 🌸" : "Next Question →"}
          </button>
        )}
      </div>

      {showSheet && (
        <div style={styles.overlay} onClick={(e) => { if (e.target === e.currentTarget) setShowSheet(false); }}>
          <div style={styles.sheetPanel} ref={sheetRef}>
            <div style={styles.sheetHeader}>
              <div style={styles.sheetTitle}>🌸 Particle Cheat Sheet</div>
              <button style={styles.closeBtn} onClick={() => setShowSheet(false)}>Close ✕</button>
            </div>
            {CHEAT_SHEET.map((entry) => (
              <div key={entry.particle} style={styles.particleBlock}>
                <div style={styles.particleLabel}>「{entry.particle}」</div>
                {entry.uses.map((u, i) => (
                  <div key={i} style={styles.useItem}>• {u}</div>
                ))}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
